kind: Service
apiVersion: v1
metadata:
  name: exchange-rate-publisher
  labels:
    app: exchange-rate-publisher
spec:
  selector:
    app: exchange-rate-publisher
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rate-publisher
  labels:
    app: exchange-rate-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-rate-publisher
  template:
    metadata:
      labels:
        app: exchange-rate-publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "exchange-rate-publisher"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: exchange-rate-publisher
        image: maciejbanas/exchange-rate-publisher:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always