apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-currency-service
  labels:
    app: node-currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-currency-service
  template:
    metadata:
      labels:
        app: node-currency-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "node-currency-service"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node-currency-service
        image: michalbarczyk/node-currency-service:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
